[project]
name = "loop-calendar"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "Kirill Ignatyev", email = "might.rubbles42@icloud.com" }
]
requires-python = ">=3.14"
dependencies = []

[project.scripts]
loop-calendar = "loop_calendar:main"

[build-system]
requires = ["uv_build>=0.12.5,<0.13.0"]
build-backend = "uv_build"

[dependency-groups]
dev = [
    "bandit>=1.9.4",
    "basedpyright>=1.39.10",
    "pyclean>=3.7.0",
    "pytest>=9.1.1",
    "pytest-cov>=7.1.0",
    "ruff>=0.16.4",
]
